### ISSUE TITLE
In android browser, Maximization -> Restore  is breaking the dialog

### ISSUE THREAD

**Issue by donino** [ROMB/jquery-dialogextend#13]
Thank you for this very nice plugin! I noticed a bug in default android browser. 

Steps to reproduce:

1- Use an Android tablet and the default stock browser (or for example use this online emulator: https://www.manymo.com/emulators)
2- Go to the latest demo page: http://jsbin.com/ehagoy/154
3- Maximize the dialog
4- Restore the dialog 
At this stage the dialog is broken: it is restored to its original size, but it is stuck on the right of the screen and we can't click any button. It seems the dialog is "transparent", we actually click on page elements which are behind the dialog.

With other tablet browsers such safari, opera or chrome for Android, everything runs fine. It only happens with Android stock browser, which is unfortunately the most widely used with tablets. Furthermore, it is only related to the transition between Maximization and Restore states, all other actions work as expected.

Any idea / workaround about this issue?

Thanks!

**Comment by josephmiller2000** [comment]
This appeared again in, chrome latest browser ( in mobile version ). Please update and let me know.
