### ISSUE TITLE
Can we open Url ??

### ISSUE THREAD

**Issue by ajaybairagi** [ROMB/jquery-dialogextend#28]
Hello,
I want to open different url page
is it possible can open URL ??
I like http://fstoke.me/jquery/window/ with min/max  popup funcinility

**Comment by ROMB** [comment]
You can include iframe into dialog window, which can open any URL you want.

**Comment by ajaybairagi** [comment]
Hello,
I have replaced text to url. I think I do something  wrong. Should you give  iframe code.

$("#my-form [name=event]").each(function(){
      if ( $(this).is(":checked") ) {
        dialogExtendOptions[$(this).attr("rel")] = function(evt, a,b,c) {
          //$(evt.target).prepend(evt.type+"@"+evt.timeStamp);
		  $(evt.target).prepend('http://localhost//example.html');
        };
      }
    });

**Comment by ROMB** [comment]
http://www.w3schools.com/html/html_iframe.asp
